require "bundler/gem_tasks"
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :spec

task :console do
  # Load in the MegaLotto module and add the lib/ directory to the load path
  exec 'irb -r mega_lotto -I ./lib'
end
